"""Generates the app icons (Android adaptive + legacy, iOS) from design/app_icon.jpg.

The source is the bot reading a book on a flat, light background. Each
platform crops icons differently, so the artwork is scaled to fit:

- Android adaptive icon: launchers show any shape inside the central circle
  of radius 33/108 of the layer (the "safe zone"), so the farthest pixel of
  the artwork is scaled to that radius. Background layer = the source's own
  background color, so the foreground can stay opaque.
- Android legacy icon (< 8.0): a round icon filling its square.
- iOS: a square without transparency; iOS rounds the corners itself.

Needs Pillow. Run from the repo root:

    python tool/make_app_icon.py
"""

import json
import math
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageStat

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design/app_icon.jpg"
ANDROID_RES = ROOT / "android/app/src/main/res"
IOS_ICONS = ROOT / "ios/Runner/Assets.xcassets/AppIcon.appiconset"

# Radius the artwork's farthest pixel may reach, as a fraction of half the
# canvas: Android's safe zone (33/54), a round legacy icon, iOS's rounded square.
ADAPTIVE_RADIUS = 0.60
LEGACY_RADIUS = 0.90
IOS_RADIUS = 0.80

DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}


def background_color(img):
    """Mean color of the source's outer border (it's flat)."""
    w, h = img.size
    strips = [(0, 0, w, 40), (0, h - 40, w, h), (0, 0, 40, h), (w - 40, 0, w, h)]
    means = [ImageStat.Stat(img.crop(b)).mean for b in strips]
    return tuple(round(sum(m[i] for m in means) / len(means)) for i in range(3))


def artwork_radius(img, bg):
    """Distance from the center to the farthest pixel that isn't background."""
    w, h = img.size
    mask = ImageChops.difference(img, Image.new("RGB", img.size, bg)).convert("L")
    mask = mask.point(lambda v: 255 if v > 14 else 0)
    px = mask.load()
    far = 0.0
    for y in range(0, h, 2):
        for x in range(0, w, 2):
            if px[x, y]:
                far = max(far, math.dist((x, y), (w / 2, h / 2)))
    return far


def fit(img, bg, far, size, radius):
    """The source scaled so its artwork reaches `radius` of a size x size square."""
    scale = (radius * size / 2) / far
    scaled = img.resize((round(img.width * scale), round(img.height * scale)), Image.LANCZOS)
    canvas = Image.new("RGB", (size, size), bg)
    canvas.paste(scaled, ((size - scaled.width) // 2, (size - scaled.height) // 2))
    return canvas


def round_icon(square):
    big = square.resize((square.width * 4, square.height * 4), Image.LANCZOS).convert("RGBA")
    mask = Image.new("L", big.size, 0)
    ImageDraw.Draw(mask).ellipse([0, 0, big.width - 1, big.height - 1], fill=255)
    big.putalpha(mask)
    return big.resize(square.size, Image.LANCZOS)


def main():
    src = Image.open(SOURCE).convert("RGB")
    bg = background_color(src)
    far = artwork_radius(src, bg)
    hex_bg = "#%02X%02X%02X" % bg
    print(f"background {hex_bg}, artwork radius {far / (src.width / 2):.2f} of half the image")

    for density, k in DENSITIES.items():
        folder = ANDROID_RES / f"mipmap-{density}"
        # Adaptive foreground: a 108 dp layer.
        fit(src, bg, far, round(108 * k), ADAPTIVE_RADIUS).save(folder / "ic_launcher_foreground.png")
        # Legacy launcher icon: 48 dp, round.
        round_icon(fit(src, bg, far, round(48 * k), LEGACY_RADIUS)).save(folder / "ic_launcher.png")

    anydpi = ANDROID_RES / "mipmap-anydpi-v26"
    anydpi.mkdir(exist_ok=True)
    (anydpi / "ic_launcher.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tool/make_app_icon.py. -->\n"
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/ic_launcher_background" />\n'
        '    <foreground android:drawable="@mipmap/ic_launcher_foreground" />\n'
        "</adaptive-icon>\n",
        encoding="utf-8", newline="\n")

    contents = json.loads((IOS_ICONS / "Contents.json").read_text(encoding="utf-8"))
    for image in contents["images"]:
        points = float(image["size"].split("x")[0])
        size = round(points * int(image["scale"].rstrip("x")))
        fit(src, bg, far, size, IOS_RADIUS).save(IOS_ICONS / image["filename"])

    fit(src, bg, far, 512, IOS_RADIUS).save(ROOT / "docs/app_icon.png")
    print(f"icons written; set ic_launcher_background to {hex_bg} in values/colors.xml")


if __name__ == "__main__":
    main()
