# flutter_gemma: rules from its README (release builds with R8).
-keep class com.google.mediapipe.** { *; }
-dontwarn com.google.mediapipe.**
-keep class com.google.protobuf.** { *; }
-dontwarn com.google.protobuf.**

# Referenced by MediaPipe but not shipped; generated by R8 (missing_rules.txt).
-dontwarn com.google.auto.value.extension.memoized.Memoized
